spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool-size: ${DB_POOL_SIZE}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
jwt:
  secret: ${JWT_SECRET}
